--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##TEST"."STUDENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TEST.STUDENT
SET DEFINE OFF;
Insert into C##TEST.STUDENT (ID,NAME,AGE,SEX) values ('001','zhangsan','18','male');
Insert into C##TEST.STUDENT (ID,NAME,AGE,SEX) values ('002','lisi','20','female');

--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "C##TEST"."SUBJECT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(20 BYTE), 
	"TEACHER" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TEST.SUBJECT
SET DEFINE OFF;
Insert into C##TEST.SUBJECT (ID,SUBJECT,TEACHER,DESCRIPTION) values ('1001','Chinese','Mr.Wang','the exam is easy');
Insert into C##TEST.SUBJECT (ID,SUBJECT,TEACHER,DESCRIPTION) values ('1002','math','Miss Liu','the exam is difficult');

--------------------------------------------------------
--  DDL for Table SCORE
--------------------------------------------------------

  CREATE TABLE "C##TEST"."SCORE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"SUBJECT_ID" VARCHAR2(20 BYTE), 
	"SCORE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TEST.SCORE
SET DEFINE OFF;
Insert into C##TEST.SCORE (ID,STUDENT_ID,SUBJECT_ID,SCORE) values ('1','001','1001','80');
Insert into C##TEST.SCORE (ID,STUDENT_ID,SUBJECT_ID,SCORE) values ('2','002','1002','60');
Insert into C##TEST.SCORE (ID,STUDENT_ID,SUBJECT_ID,SCORE) values ('3','001','1001','70');
Insert into C##TEST.SCORE (ID,STUDENT_ID,SUBJECT_ID,SCORE) values ('4','002','1002','60.5');
